name: Richi
favicon: null
layout_spectrum: 0.2522
typography_spectrum: 0.3901909014675766
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8700325188692659
  lightness: 0.08720580628141761
  saturation: 0.7209045432973653
  rhythmicContrast: 0.05722649744711816
purpose: []
